#version: "3.8"

services:
  node-app:
    container_name: node-app
    # build:
    # context: .
    image: 488626125052.dkr.ecr.eu-west-2.amazonaws.com/node-app:latest
    depends_on:
      - postgres-db
    restart: unless-stopped
    environment:
      DB_HOST: "postgres-db"
      DB_USER: "yele"
      DB_PASS: "secret"
      DB_NAME: "demo"
      DB_PORT: "5432"
      PORT: 5002
    ports:
      - 8080:5002
    volumes:
      - .:/www/app
    networks:  # Reference the network here
      - altsch-network

  postgres-db: 
    container_name: node-app
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "yele"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5001:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:  # Reference the network here
      - altsch-network

volumes:
  postgres-data:

networks:  # Define the network at the root level
  altsch-network: 
    driver: bridge